CONTROLLER: Home
Mums-Who-Code/MyPortfolio.Services pull request #24
Opened 2021-11-21 05:34 UTC by Nighila

![image](https://user-images.githubusercontent.com/89492890/142750966-ed7d63f5-0d36-476a-bc0e-94fff906d761.png)

Closes #23

2021-11-21 06:27 UTC, ShriHumrudha requested changes

2021-11-21 06:27 UTC, ShriHumrudha commented on MyPortfolio.services.api/Controllers/HomeController.cs
> +
remove empty line

2021-11-21 06:27 UTC, ShriHumrudha commented on MyPortfolio.services.api/Controllers/HomeController.cs
> +        Ok("Check whether System or API End points are responding properly or not");
Need one tab indentation

2021-11-21 06:38 UTC, Nighila commented on MyPortfolio.services.api/Controllers/HomeController.cs
> +
Fixed

2021-11-21 22:40 UTC, ShriHumrudha approved these changes

2021-11-23 02:02 UTC, juturul approved these changes

2021-11-23 02:02 UTC, NaynaMallick approved these changes

2021-11-23 02:51 UTC, Shrabanac approved these changes

2021-11-28 04:13 UTC, merged