BROKER: Insert Participant
Mums-Who-Code/MyPortfolio.Services pull request #38
Opened 2022-02-04 02:40 UTC by Nighila

Closes #37

2022-02-05 06:27 UTC, ShriHumrudha requested changes

2022-02-05 06:27 UTC, ShriHumrudha commented on MumsWhoCode.Services.api/Brokers/Storages/IStorageBroker.Participant.cs
> +        ValueTask<Participant> InsertCategoryAsync(Participant participant);
Correct method name.

2022-02-07 04:25 UTC, ShriHumrudha approved these changes

2022-02-07 18:53 UTC, NaynaMallick approved these changes

2022-02-10 00:58 UTC, merged